campaign_end:
  # at: 2:30
  cron: "30 2 * * * America/New_York"
  class: "ResqueSchedule::CampaignEnd"
  queue: high
  description: "Triggers the @coupon_book.end method on campaigns that have reach their end_date"
commission_transfers:
  # at: 1:30
  cron: "30 1 * * * America/New_York"
  class: "ResqueSchedule::CommissionTransfer"
  queue: high
  description: "Transfers all commissions to users' Stripe Accounts."