campaign_end:
  # every:
  #   - "1m"
  cron: "* * * * * America/New_York"
  class: "ResqueSchedule::CampaignEnd"
  queue: high
  description: "Triggers the @campaign.end method on campaigns that have reach their end_date"

transfer_payments:
  # every:
  #   - "1d"
  cron: "0 0 * * * America/New_York"
  class: "ResqueSchedule::TranferPayments"
  queue: high
  description: "Transfers funds to fundraisers's Stripe accounts"

